version: "3.9"

services:
  node-backend:
    build: ./node-backend
    container_name: node-backend
    expose:
      - "5000"
    env_file:
      - ./node-backend/.env
    networks:
      - backend-network

  fastapi-backend:
    build: ./fastapi-backend
    container_name: fastapi-backend
    expose:
      - "8000"
    env_file:
      - ./fastapi-backend/.env
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-backend
      - fastapi-backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
